### ISSUE TITLE
Style Guidelines

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#11]
I just wanted to ask if there is a plan to support rustfmt style guidelines. I am usually quite the fan of making everything unfiform unless there is a specific reason to not do it.

Having the default or a modified rustfmt as a style guideline might be worth looking into.

**Comment by dogamak** [comment]
Yes, this is probably a good idea. I don't really have any strong opinions about formatting, but some uniformity would be great though.

However [this](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/example/lists.rs#L95-L104) format is recommended by rustfmt, but strikes me as a bit weird. However I like the dangling comma after the last argument.

**Comment by chrisduerr** [comment]
I personally rather get used to some odd things than having to remember the style guide and everything myself. There definitely are some options for configuration tho.

Setting `where_style = "Legacy"` would change it into this, for example:
```
pub fn list_helper<I>(
    items: I,
    width: usize,
    offset: i32,
    config: &i32,
    tactic: i32,
) -> Option<String>
    where I: Iterator<Item = i32>
{
    None
}
```

**Comment by dogamak** [comment]
Yeah, I think the default format is okay. Should I run `rustfmt` on the whole repo?

**Comment by chrisduerr** [comment]
I wasn't able to make it work properly on all files so it might need some manual guidance for a few of them. If you want to I can go through every file and try to send a PR with `rustfmt` working.

It seems like formatting inside of macros (both definition and execution) is not supported I just noticed. So there might still be some manual intervention required.

**Comment by dogamak** [comment]
I'd appreciate if you did that. It was to be expected that `rustfmt` wouldn't work on macros. They are basically new and custom syntax, so how'd it know what it is supposed to look like.

**Comment by chrisduerr** [comment]
I've sent a PR for the complete `rustfmt` and it worked okay.
Besides `rustfmt` I've also seen that there are a few of `clippy` lints that could be resolved. Is `clippy` intentionally not used or would this be another thing that could be investigated?

**Comment by dogamak** [comment]
Yes, enabling clippy was something I was planning to do after I get Travis all set up. However there was some problems   (#9).
