### ISSUE TITLE
Ability to configure inner padding at the ends of the bar

### ISSUE THREAD

**Issue by dogamak** [dogamak/xcbars#14]

**Comment by chrisduerr** [comment]
Are we just talking about spacers at the left and right side of the bar? Maybe making that a component would be a good idea. So just a spacer which could be specified in pixels or percentage that can be inserted anywhere.

**Comment by dogamak** [comment]
Ah, that's a good idea. But I think we should have `set_padding` or similar in the `BarBuilder`, because just having padding at the both ends of the bar is such a common thing to want. And all it would require is probably an additon/substraction in `redraw_left`/`redraw_right`. 

Could you create a separate issue for the spacer component?

**Comment by chrisduerr** [comment]
Hmm yeah I guess it is pretty common. If a spacer component exists it would be both possible to automatically insert that or just set a boundary to the drawing area the way you described. Offering an option to do it from the `BarBuilder` is probably just nice to have in that case and will not really make things more complicated.

And @dogamak you can just add the spacer to the components issue that already exists. I don't think it needs elaboration or a specific issue until there is any concrete plan of implementation or problem.

**Comment by chrisduerr** [comment]
Also there already is a `padding_x` in `Geometry::Relative` which just seems to put a padding at the right side of the bar. So maybe that can be changed into `padding_left` and `padding_right`?

**Comment by dogamak** [comment]
`padding_x` configures the outter padding of the bar, this issue is for the inner padding.
