### ISSUE TITLE
Slot not working properly

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#17]
While testing my changes I've noticed that it doesn't look like `Slot` is working properly. Specifying `Slot::Center` or `Slot::Right` will lead to the component not showing up at all. Using `Slot::Left` seems to work, however specifying it for multiple elements will cause them to be rendered over each other, instead of next to each other.

**Comment by dogamak** [comment]
Shit. Works on my machine™.

**Comment by dogamak** [comment]
Here's my working config [in a gist](https://gist.github.com/dogamak/05eb8063c952b8400f13d6fb3efe7336) .

**Comment by dogamak** [comment]
Oh right, I remember fixing warning on unnecessarily mutable variable `pos`, so I propably just forgot to increment it in `redraw_left`.

**Comment by dogamak** [comment]
f7dac59 fixes the positioning bug, but some components are still not shown. They are probably rendered, but being drawn over with background afterwards.

**Comment by dogamak** [comment]
@chrisduerr can you confirm you aren't experiencing the rendering issues anymore with the `fix-17` branch?

**Comment by chrisduerr** [comment]
I can confirm that the elements are not rendered above each other anymore, however `Slot::Center` and `Slot::Right` still do not work.

**Comment by chrisduerr** [comment]
So I've just checked again with only one output plugged in and everything worked properly. Upon checking the position of the left and center elements I noticed that it is taking the width of all my outputs, not only the one the bar is being displayed on.

So I guess this is a multihead issue.
https://github.com/dogamak/xcbars/blob/44d06618e6ec99efab6ba96206104688a11f6f97/src/bar_builder.rs#L269

**Comment by dogamak** [comment]
I opened an issue for multihead support at #18.
