### ISSUE TITLE
Geometry::Relative padding_y not working

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#24]
So either I'm just really blind or the `padding_y` in `Geometry::Relative` doesn't change anything. I'd suppose this should be an offset from the top? So with increasing `padding_y` the text is lower and lower? Or is this supposed to be a padding around the bar, so that the bar would have gaps at the side? If this is the case then `padding_x` also wouldn't work properly.

Either way tho I don't see `padding_y` changing anything, `padding_x` does change something but doesn't seem very useful.

**Comment by dogamak** [comment]
`padding_y` and `padding_x` are supposed to be the paddings around and outside the bar window. That is, the space to the display borders.

**Comment by chrisduerr** [comment]
Oh okay. Then both those do not work for me. Do they work on your single-screen setup? I still am running my other bar next to it, so that might be causing some issues too.

**Comment by dogamak** [comment]
I doubt the other bar causes any issues. The both the x and the y padding settings worked before #19, but I haven't checked since.

**Comment by chrisduerr** [comment]
It would probably help with narrowing the problem down if you would check again.

**Comment by dogamak** [comment]
They seem to be working properly for me with the current master. With both `Position::Top` and `Position::Bottom`.

**Comment by chrisduerr** [comment]
Well `Position::Bottom` doesn't work for me at all. Might be related.

**Comment by chrisduerr** [comment]
Well `Position::Bottom` doesn't work for me at all. I'm running i3 with compton. I've tried disabling both my other bar and compton and couldn't make padding or `Position::Bottom` work. Any idea how I could further troubleshoot?

Could it have something to do with the struts?
<https://github.com/dogamak/xcbars/blob/master/src/bar_builder.rs#L420-L424>

**Comment by dogamak** [comment]
Does it work in the other monitor? Does it work without the other monitor? `println!` and check whether the calculated window coordinates are right or not. Do you have any other WM installed? If so, try with it.

It could be because [we set EWMH struts incorrectly](https://github.com/dogamak/xcbars/blob/master/src/bar_builder.rs#L420-L424) if the bar is positioned at the bottom, and i3 is overly sensitive for it.

**Comment by chrisduerr** [comment]
I've tried on multiple monitors and with all but one turned off. Nothing worked. The EWMH struts are the thing that seems most likely to me.

The window coordinates also seemt to be correct.

**Comment by chrisduerr** [comment]
Apparently i3wm doesn't support partial width on dock clients. So implementing this using struts might not be the way to go. An option that would work on every WM with a compositor is using transparency to add paddings to the bar window. Otherwise I don't see a way to support this feature on i3.

This will require #21 to be implemented first.
