### ISSUE TITLE
Center component not properly redrawing itself

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#30]
So I'm currently implementing the active window title component and it already works pretty well. However with the center slot it doesn't properly display the text correctly. If I have an element that is longer than the current one, it doesn't clean up the previous element but just draws it over the old one. This results in parts of the old one remaining at the left and right side of the current title.

I don't see how this would be due to an error in my window title component. But I thought I should still ask if it might be, before sending a PR.

**Comment by dogamak** [comment]
Yes, any rendering issues shouldn't be caused by individual Component's implementation. Feel free to ignore the issue and make a PR for the component.
