### ISSUE TITLE
_NET_WM_NAME and WM_NAME

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#33]
It seems like both `_NET_WM_WINDOW_NAME` and `WM_NAME` are both supported properties for the name of a window. EWMH recommends `_NET_WM_NAME` but as far as I can see only `WM_NAME` is supported by i3 and that's what I've been using to test.

So there might be some testing needed if setting the window name works on all systems. It would probably be advisable to set both `_NET_WM_NAME` and `WM_NAME`.

**Comment by dogamak** [comment]
Pre-EWMH stuff (e.g. `WM_NAME`) seems to be considered largely deprecated. For example Qt doesn't set `WM_NAME` at all. EWHM spec suggests that developers should prefer `_NET_WM_NAME` over `WM_NAME`, but that's only a suggestion.

**Comment by chrisduerr** [comment]
Yeah so we should probably support both. Right now there only is `ATOM_WM_NAME` used, so we might need to add the `_NET_WM_NAME`. It should be required when setting the name of the bar and in the window title component. Are you able to test this? Because I don't think I have anything that uses `_NET_WM_NAME`. I generally can't really seem to make the `_NET_` components work tho, but i3 does support ewmh as far as I know.
