### ISSUE TITLE
Open PRs

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#41]
So I understand that time might be limited @dogamak, but I wanted to ask if there is any special reason why you haven't commented on many of my PRs at all.

The Fix center PR I've opened two weeks ago and I just wanted to check in if PRs are actually welcome or if you would prefer to handle this project yourself.

**Comment by dogamak** [comment]
Yeah, sorry. In the last few weeks I have experienced radical reduction of my free time while still having to self-study. Your work is appreciated and I'll promise to sort out the PRs this evening.

**Comment by chrisduerr** [comment]
That's appreciated. As long as I know what's up I can adjust. :D

**Comment by dogamak** [comment]
Well. Making them all fail _is_ one solution to having too many ready-to-merge PRs. :smile:

**Comment by chrisduerr** [comment]
:)

**Comment by chrisduerr** [comment]
@dogamak This project has been stale for quite a while now again. If you want to keep working on this, do you have an ETA on when you will have more time again?

Right now it seems like any PR is just gonna pile up without being merged. So I am unsure if it is worth contributing until you have the time to merge PRs.
