### ISSUE TITLE
Pangocairo breaking again

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#42]
While trying to fix the clippy issue I just ran into this issue:
https://travis-ci.org/chrisduerr/xcbars/jobs/254981520

It looks like pango cairo got broken again?
This should not be limited to my version.

**Comment by dogamak** [comment]
RazrFalcon fixed this with https://github.com/RazrFalcon/pangocairo-rs/commit/fe89e5254f60b2a6c73fb1935b82574b4d21b290 5 hours ago.
