### ISSUE TITLE
Replacing LoopFN with Interval

### ISSUE THREAD

**Issue by chrisduerr** [dogamak/xcbars#45]
So recently when editing the network and window title components I've used `timer.interval_at` to start a loop. However the other components all use `LoopFn`. Why would I use `LoopFn` over `interval`?

I don't quite understand why we need our own wrapper to loop and sleep when we can just use an interval. `interval_at` also allows us to start immediately using `time::Instant::now()` so we do not have to wait the specified time until the method is invoked the first time.

**Comment by dogamak** [comment]
`LoopFn` was introduced before `tokio-timer` was used at all. `Timer::interval_at` is definitely better way to do this if the loop is interval based. `LoopFn` was initially used to run the same external command repeatedly with no time between the runs.
