### ISSUE TITLE
Get Travis to build this somehow

### ISSUE THREAD

**Issue by dogamak** [dogamak/xcbars#9]
The build fails because the build of `xcb-rust` fails, which is propably because the host system doesn't have XCB libraries installed.

**Comment by dogamak** [comment]
Configured travis to install the needed c libraries in d04027d6c354c92d9a2459f26608fd6fd98b4f07 and 0d2b5450ab779c44def2b236bbefc762ccea20b3, but it seems like that Travis boxes don't have pango 1.3.0 which is required by `pangocairo` crate.

**Comment by dogamak** [comment]
Actually that was because I wrong packages... But now the crate `pangocairo` fails because the boxes have only 1.36.1 of `libpangocairo` instead of the required 1.38.0.

**Comment by chrisduerr** [comment]
gtk-rs has a .travis.yml and I'd assume this might help?
https://github.com/gtk-rs/gtk/blob/master/.travis.yml
Don't have an experience with travis but maybe the libgtk dependency can help?

**Comment by dogamak** [comment]
There's currently as far as I know no other problems than getting version `>=1.38.0` of `libpangocairo` installed on the Travis box.
I am not familiar with Ubuntu, but I doubt it's possible to just install `.deb` from a newer version of Ubuntu without having to fight the dependency hell...

**Comment by dogamak** [comment]
Unfortunately I see no way to get this to work on Travis. Options are to either fork `pangocairo-rs` and make it work with our version of `libpangocairo` or use a different CI. I don't think there's any point to the former just to get CI working, so we'll probably have to ditch Travis.

**Comment by chrisduerr** [comment]
I've played around on a VPS and installing a deb definitely creates dependency hell. I can look a little further into this, however I'm not sure if it's gonna lead to anything.

Do you know why `gtk-rs` is able to build using cairo?

**Comment by chrisduerr** [comment]
https://github.com/travis-ci/travis-ci/issues/5821
This indicates that it might be an option to use a xenial docker image to build.

**Comment by dogamak** [comment]
Ah, you are right. If docker works, that means we can use an existing rust image like [jimmycuadra/rust](https://hub.docker.com/r/jimmycuadra/rust/~/dockerfile/).  `Dockerfile` could propably be hosted in this repo and use that to build the project from the image.

Jimmycuada's image is based on debian and not ubuntu, but it seems to contain `libpangocairo 1.40.0` in it's repos.

**Comment by chrisduerr** [comment]
That sounds like a good idea. And it should be pretty straight-forward.

**Comment by dogamak** [comment]
What, no I didn't, it says "*Attempts* to resolve"!

**Comment by dogamak** [comment]
Should be fixed with 5ed863604a3334b40976a0281fbaa17f0e68f2c9.
